# Generated by Django 5.2.6 on 2025-11-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='activityoverride',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='activityrule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cityactivitygallery',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='cityextra',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='instructormedia',
            options={'managed': True, 'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='instructorreview',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='instructorsubscription',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='populardestination',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='schoolblog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='schooleffectiveplan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='schoolreview',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
