# Generated by Django 5.2.6 on 2025-11-17 19:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_card',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_card'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
