# Generated by Django 5.2.6 on 2025-11-17 21:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_activity_image_card_alter_activity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
    ]
