# Generated by Django 5.2.6 on 2025-10-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytemplate',
            options={'managed': True, 'verbose_name': 'Activity Template', 'verbose_name_plural': 'Activity Templates'},
        ),
    ]
