# Generated by Django 5.2.6 on 2025-11-17 22:14

from django.db import migrations
import cloudinary.models

class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_activity_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hero_image',
            field=cloudinary.models.CloudinaryField("hero_image", blank=True, null=True),
        ),
    ]