# Generated by Django 5.2.6 on 2025-11-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_booking_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='variant',
            field=models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='directory.schoolactivityvariant'),
        ),
        migrations.AddField(
            model_name='booking',
            name='school',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.CASCADE, related_name='bookings', to='directory.school'),
        ),
    ]
