# Generated by Django 5.2.6 on 2025-11-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_booking_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolactivityvariant',
            name='levels',
        ),
        migrations.AddField(
            model_name='schoolactivityvariant',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolactivityvariant',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolactivityvariant',
            name='equipment_items',
            field=models.JSONField(blank=True, help_text="Equipos disponibles para alquiler si offer_type='rental'. Ejemplo: ['Tabla', 'Leash', 'Neoprene']", null=True),
        ),
        migrations.AddField(
            model_name='schoolactivityvariant',
            name='included_services',
            field=models.JSONField(blank=True, help_text="Lista de servicios incluidos: ['Accommodation', 'Meals', 'Transport', ...]", null=True),
        ),
        migrations.AddField(
            model_name='schoolactivityvariant',
            name='pack_description_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolactivityvariant',
            name='pack_title',
            field=models.CharField(blank=True, help_text="Título o nombre comercial del paquete si offer_type='pack'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolactivityvariant',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('extreme', 'Extreme')], help_text="Indica el nivel de dificultad si aplica (solo para offer_type='lesson' o 'course').", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='schoolactivityvariant',
            name='experience_type',
            field=models.CharField(blank=True, choices=[('oneshot', 'One Shot'), ('adventure', 'Adventure'), ('expedition', 'Expedition')], help_text="Indica el tipo de experiencia si offer_type='experience'.", max_length=32, null=True),
        ),
    ]
