# Generated by Django 5.2.6 on 2025-11-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_booking_partial_percent_booking_payout_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltransaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='directory.booking'),
        ),
        migrations.AddField(
            model_name='schooltransaction',
            name='is_released',
            field=models.BooleanField(default=False, help_text='Indica si el pago ya fue transferido a la escuela.'),
        ),
        migrations.AlterField(
            model_name='schooltransaction',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Porcentaje de comisión aplicado', max_digits=5),
        ),
    ]
