# Generated by Django 5.2.6 on 2025-11-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_alter_payment_stripe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_payout_sent',
            field=models.BooleanField(default=False),
        ),
    ]
